### ISSUE TITLE
GitHub user access cleanup

### ISSUE THREAD

**Issue by dougwilson** [expressjs/expressjs.github.io#10]
Hi @expressjs/owners, I'm working on auditing the current owners of the expressjs organization. If any of you think you don't need to actually be an owner, please let me know as a comment here or by email and I can remove you (I also think you have the ability to remove yourself).

I'm also going to be demoting the current owners that do not have 2FA on their GitHub account to just members of the organization for now. If you are affected, and want to be promoted back to an owner, please let me know 1) that you have setup 2FA on your GitHub account or 2) why you can't enable it (perhaps there is a legitimate reason).

I'm also doing some team cleanup, which may not really affect the owners here, but it also shouldn't affect anyone's access, just converting things to the new permissions model.

**Comment by defunctzombie** [comment]
I don't need owner access anymore. If there are issues or contributions, I will open a PR.

**Comment by dougwilson** [comment]
Thanks for the response, @defunctzombie ! I'm leaning some more still about all the new settings, as there are so many now :) I have converted you to an "outside collaborator", which I think in general just means jshttp is just another GitHub org to you. Let me know if you wanted to be something else, as I don't intend to make any changes you don't want :)

**Comment by troygoode** [comment]
@dougwilson 2FA is now enabled. thanks for the push; I was being lazy about it :-)

**Comment by dougwilson** [comment]
No problem, @troygoode , I added you back as an owner :)

**Comment by joewagner** [comment]
@dougwilson I've got 2FA.  I haven't contributed much lately, and I'm happy to fill whichever role you see fit.  I can always send PRs :D

**Comment by Fishrock123** [comment]
I have 2FA enabled, fwiw.

I can’t guarantee my involvement, but also don’t mind saying an owner for some ownership distribution.

~Jeremiah

**Comment by dougwilson** [comment]
Thanks, everyone! I'm going to close this issue now.

**Comment by dougwilson** [comment]
I changed @ritch and @hacksparrow back to owners, at the request of @ritch, though they do not have 2FA enabled.

@ritch and @hacksparrow please setup 2FA on your GitHub account as soon as possible, or provide why you can't enable it (perhaps there is a legitimate reason).
