### ISSUE TITLE
future plans

### ISSUE THREAD

**Issue by jonathanong** [expressjs/expressjs.github.io#6]
this express situation isn't going to resolve itself anytime soon because foundations take time and express isn't going to be the priority. there are few short-term courses of action:

1. "fork" express, though really we'll just be creating a new framework. personally, i'm not really interested unless it's inherently promise-based. but i don't think we maintainers should just completely ditch the express ecosystem.
2. piggy back on another framework like sails. like how express ditched connect, sails could ditch express, and we could try to make it more modular. or we could just move all the express stuff to a sails org or something.
3. move all the "utilities" to some sort of "node-web-framework-utils" org.  https://github.com/expressjs/expressjs.github.io/issues/2

these aren't all mutually exclusive, but i want 3) just for code organization. there are a lot of TJ's web modules that he didn't feel like transferring here because they weren't exactly express related. we could fork and continue maintaining them in this organization.

cc @rlidwka @mikermcneil

**Comment by dougwilson** [comment]
Closing this issue, as it is pretty stale now.
