### ISSUE TITLE
WebSockets Support

### ISSUE THREAD

**Issue by ericrange** [expressjs/expressjs.github.io#9]
Hey what about web sockets support?

if you have a route like:
```
router.get("...")
```
There should listen simultaneously a web socket for the same route and do exactly the same whether if xhr oder web socket request.

That could be a really nice thing, especially for modern browsers. No delay anymore...

Just an idea ;)

**Comment by dougwilson** [comment]
Hi! I believe you are looking to create this issue over at the main Express repository (https://github.com/strongloop/express).

There has been an open issue about this for some time (https://github.com/strongloop/express/issues/2594) and the only thing topped us is someone offering up a PR to add the functionality.
